//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company {
	
	
	public partial class Register {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox emailTB;
		
		protected System.Web.UI.WebControls.TextBox passwordTB;
		
		protected System.Web.UI.WebControls.TextBox fnameTB;
		
		protected System.Web.UI.WebControls.Button B1;
	}
}
